---
title: "Consequences of Severe Weather Events"
author: "Thomas Bell"
date: "31 juli 2017"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Synopsis

Does the analysis address the question of which types of events are most harmful to population health?

Does the analysis address the question of which types of events have the greatest economic consequences?

## Data Processing

### Reading raw data
```{r raw-data, cache = TRUE}
library(dplyr)
library(xlsx)
library(lubridate)

df <- read.csv("repdata%2Fdata%2FStormData.csv.bz2")

## downloaded from https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2 on 31-7-2017 16:00 CET

fips <- read.xlsx("fips_codes_website.xls", sheetIndex=1, header=TRUE) 

## downloaded from http://www.census.gov/2010census/xls/fips_codes_website.xls on 2-8-2017 12:50 CET

```


### Consolidating and removing not needed data
```{r consolidating}
# Drop not needed columns and convert date into Date class
df %>% select(c(1:2,7:29)) %>% mutate(BGN_DATE = mdy(gsub(" .*","", df$BGN_DATE))) -> proc_df

# Before rationalising there are 985 levels
nlevels(proc_df$EVTYPE)

# After toupper() there are 898 levels
proc_df$EVTYPE <- toupper(proc_df$EVTYPE)
length(unique(proc_df$EVTYPE))

# Including only measurements from 1996 (year recording of all weather types started)
proc_df <- filter(proc_df, BGN_DATE > 1996)

# Roughly merge biggest types with spelling / coding issues
proc_df$EVTYPE[grep("^TSTM|^THUNDERSTORM|^THUNDERSTORMS", proc_df$EVTYPE)] <- "THUNDERSTORM WIND"
proc_df$EVTYPE[grep("^MARINE TSTM|^MARINE THUNDERSTORM", proc_df$EVTYPE)] <- "MARINE THUNDERSTORM WIND"
proc_df$EVTYPE[grep("^FLASH|^FLOOD FLASH|FLOOD/FLASH", proc_df$EVTYPE)] <- "FLASH FLOOD"
proc_df$EVTYPE[grep("^RIP", proc_df$EVTYPE)] <- "RIP CURRENT"
proc_df$EVTYPE[grep("HURRICANE|TYHPHOON", proc_df$EVTYPE)] <- "HURRICANE (TYPHOON)"
proc_df$EVTYPE[grep("^HIGH WIND", proc_df$EVTYPE)] <- "HIGH WIND"
proc_df$EVTYPE[grep("^STRONG WIND", proc_df$EVTYPE)] <- "STRONG WIND"
proc_df$EVTYPE[grep("^HEAVY RAIN|PRECIPITATION", proc_df$EVTYPE)] <- "HEAVY RAIN"
proc_df$EVTYPE[grep("WINTER WEATHER|WINTERY|WINTRY|WINTER MIX", proc_df$EVTYPE)] <- "WINTER WEATHER"

# Create frequency table for event types
freq_table <- sort(table(proc_df$EVTYPE), decreasing = TRUE)
freq_table <- as.data.frame.table(freq_table)

# Calculate percentages for weather types and filter above 1% to get weather types that cover 99% of measurements after 1996
relative <- (freq_table$Freq/sum(freq_table$Freq))*100
freq_table <- cbind(freq_table, relative)
top_types <- as.character(filter(freq_table, relative >= 1)$Var1)

# Filter processes data frame on top types
proc_df <- filter(proc_df, EVTYPE %in% top_types)
top_types
```

### Property and crop damage
```{r propcrop}
# Function to set exponent based on rules provided in analysis by David Hood https://rstudio-pubs-static.s3.amazonaws.com/58957_37b6723ee52b455990e149edde45e5b6.html

get_exponent <- function(exp) {
        exp <- tolower(exp)
        if (exp == "h") {
                out <- 100
        } else if (exp == "k") {
                out <- 1000
        } else if (exp == "m") {
                out <- 1000000
        } else if (exp == "b") {
                out <- 10000000
        } else if (exp == "+") {
                out <- 1
        } else if (as.numeric(exp) %in% 0:8) {
                out <- 10
        } else {out <- 0}
        out
}

# Converte prop and crop damage to absolute amounts
proc_df$PROPDMG <- proc_df$PROPDMG * sapply(proc_df$PROPDMGEXP, get_exponent)
proc_df$CROPDMG <- proc_df$CROPDMG * sapply(proc_df$CROPDMGEXP, get_exponent)

```

## Results

